version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - worker
    volumes:
      - .:/coverage
      - type: volume
        source: db
        target: /code/monolith/db
  monolith:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - worker
    volumes:
      - type: volume
        source: db
        target: /code/monolith/db
    ports:
      - "5000:5000"
  worker:
    build:
      context: .
    environment:
      - "BROKER=redis://redis:6379"
      - "BACKEND=redis://redis:6379"
      - "CONFIG=PRODUCTION"
    command: celery -A monolith.worker:celery worker -l info # -B -s /tmp/celerybeat-schedule
    depends_on:
      - redis
    volumes:
      - type: volume
        source: db
        target: /code/monolith/db
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
  worker-local:
    build:
      context: .
    environment:
      - "BROKER=redis://local:6379"
      - "BACKEND=redis://local:6379"
    command: celery -A monolith.worker:celery worker -l info # -B -s /tmp/celerybeat-schedule 
    volumes:
      - ./:/code
  local:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    depends_on:
      - worker-local
volumes:
  db: