version: '3'
services:
  monolith:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: db-production
        target: /code/monolith/db
    ports:
      - "5000:5000"
    environment:
      - "CONFIG=PRODUCTION"
volumes:
  db-production: