FROM python:3.7-alpine3.11
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install pytest pytest-cov
ADD . /code
WORKDIR /code
ENV BROKER=redis://redis:6379
ENV BACKEND=redis://redis:6379
RUN chmod +x /code/test.sh
CMD ["pytest", "--cov-config=/coverage/.coveragerc", "--cov=monolith"]
