name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker images
      run: docker-compose build
    - name: Run tests
      run: docker-compose up --exit-code-from tests tests
    - name: STEP 2. Set-Up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: STEP 3. Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
    - name: STEP 4. Pytest Coverage
      run: |
        pip install coveralls
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          coveralls